import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	DEFAULT_REQUEST_ATTRIBUTION,
	DEFAULT_VISION_AGENT,
	DEFAULT_VISION_INTEGRITY,
	DEFAULT_VISION_PROCESSING
} from "../config/contractConfig";
import {
	getCompatibilityMatrixEntry,
	type CompatibilityMatrixInput
} from "../toolCooperation/compatibilityMatrix";

const README = readFileSync(resolve(__dirname, "../../README.md"), "utf8");
const README_CONFIG = JSON.parse(readFileSync(resolve(__dirname, "../../docs/readme.config.json"), "utf8")) as {
	generatedNotice?: string;
	languages?: Array<{ id?: string; label?: string; anchor?: string }>;
	sectionOrder?: string[];
	generatedSections?: string[];
};
const README_SECTIONS = JSON.parse(readFileSync(resolve(__dirname, "../../docs/readme.sections.json"), "utf8")) as Record<
	string,
	{ zh?: string; en?: string; title?: { zh?: string; en?: string } }
>;
const PACKAGE_JSON = JSON.parse(readFileSync(resolve(__dirname, "../../package.json"), "utf8")) as {
	contributes?: {
		configuration?: {
			properties?: Record<string, unknown>;
		};
	};
};

test("README is generated from the checked-in multilingual config", () => {
	assert.match(
		README,
		/This README is generated by scripts\/readme\/generate-readme\.mjs from docs\/readme\.config\.json and docs\/readme\.sections\.json/
	);
	assert.deepEqual(README_CONFIG.languages?.map((language) => language.id), ["zh", "en"]);
	execFileSync(process.execPath, ["scripts/readme/readme-section-parity.mjs"], {
		cwd: resolve(__dirname, "../.."),
		stdio: "ignore"
	});
	execFileSync(process.execPath, ["scripts/readme/generate-readme.mjs", "--check"], {
		cwd: resolve(__dirname, "../.."),
		stdio: "ignore"
	});
});

test("readme.sections.json keeps zh/en parity for every sectionOrder entry", () => {
	const generated = new Set(README_CONFIG.generatedSections ?? []);
	for (const id of README_CONFIG.sectionOrder ?? []) {
		if (generated.has(id)) {
			continue;
		}
		const block = README_SECTIONS[id];
		assert.ok(block, `missing section ${id}`);
		assert.ok(String(block.zh ?? "").trim().length > 0, `empty zh for ${id}`);
		assert.ok(String(block.en ?? "").trim().length > 0, `empty en for ${id}`);
		assert.ok(block.title?.zh, `missing title.zh for ${id}`);
		assert.ok(block.title?.en, `missing title.en for ${id}`);
	}
});

test("README documents both built-in paths and the sealed 16-cell compatibility matrix", () => {
	for (const fragment of [
		"Path A",
		"Path B",
		"modelSource = vscode-lm-wrapper",
		"| builtin | vision | tools | on | native | - |",
		"| builtin | non-vision | tools | on | wrapper-proxy | - |",
		"| bro | vision | no-tools | off | native | text-fallback |",
		"| bro | non-vision | no-tools | off | disabled | - |"
	]) {
		assert.match(README, new RegExp(escapeRegExp(fragment)));
	}
});

test("README config reference stays aligned with sealed runtime defaults", () => {
	const fragments = [
		"| visionProxy | enabled | true |",
		`| visionAgent | enabled | ${String(DEFAULT_VISION_AGENT.enabled)} |`,
		`| visionAgent | keepAliveMs | ${String(DEFAULT_VISION_AGENT.keepAliveMs)} |`,
		`| visionAgent | maxBatchSize | ${String(DEFAULT_VISION_AGENT.maxBatchSize)} |`,
		`| visionAgent | maxConcurrentBatches | ${String(DEFAULT_VISION_AGENT.maxConcurrentBatches)} |`,
		`| visionAgent | resetContextPerBatch | ${String(DEFAULT_VISION_AGENT.resetContextPerBatch)} |`,
		`| visionAgent | deduplicateImages | ${String(DEFAULT_VISION_AGENT.deduplicateImages)} |`,
		`| visionAgent | retryOnFailure | ${String(DEFAULT_VISION_AGENT.retryOnFailure)} |`,
		`| visionIntegrity | strictIntegrity | ${String(DEFAULT_VISION_INTEGRITY.strictIntegrity)} |`,
		`| visionIntegrity | certaintyThreshold | ${String(DEFAULT_VISION_INTEGRITY.certaintyThreshold)} |`,
		"| (top) | includeBuiltInPresets | true |",
		"| (top) | requestTimeoutMs | 120000 |",
		"| retry | enabled | true |",
		`| visionProcessing | outputVerbosity | ${DEFAULT_VISION_PROCESSING.outputVerbosity} |`,
		`| visionProcessing | chatDebugVisibility | ${String(DEFAULT_VISION_PROCESSING.chatDebugVisibility)} |`,
		`| visionProcessing | spatialSchemaVersion | ${DEFAULT_VISION_PROCESSING.spatialSchemaVersion} |`,
		`| requestAttribution | enabled | ${String(DEFAULT_REQUEST_ATTRIBUTION.enabled)} |`,
		"- 原生视觉模型默认走 native 结构化识图",
		"Native vision defaults to the structured native pass"
	];
	for (const fragment of fragments) {
		assert.match(README, new RegExp(escapeRegExp(fragment)));
	}

	const properties = PACKAGE_JSON.contributes?.configuration?.properties ?? {};
	assert.ok(properties["extendedModels.visionProxy"]);
	assert.ok(properties["extendedModels.promptPresets"]);
	assert.ok(properties["extendedModels.requestAttribution"]);
});

test("README migration guide covers the supported legacy aliases and rollout order", () => {
	for (const fragment of [
		"`visionEnabled` | `visionAgent.enabled`",
		"`visionAgent.dedupeByHash` | `visionAgent.deduplicateImages`",
		"`visionProcessing.tokenBudgetMode` | `visionProcessing.outputVerbosity`",
		"`visionAgent.autoClosePolicy = timeout` | `afterTimeout`",
		"`visionAgent.autoClosePolicy = manual` | `never`",
		"1. 升级后先保持 `visionAgent.enabled = false`",
		"1. Upgrade while keeping `visionAgent.enabled = false`."
	]) {
		assert.match(README, new RegExp(escapeRegExp(fragment)));
	}
});

test("README includes F.3/F.4 vision prompt contract schema examples", () => {
	for (const fragment of [
		"### 视觉提示词契约与 Schema 示例",
		"vision-prompt-contract-v1",
		"roiLocalization",
		"maskGuidance",
		"edgeIssues",
		"transformHints",
		"styleConstraints",
		"### Vision Prompt Contract and Schema Examples",
		"Response skeleton (example):"
	]) {
		assert.match(README, new RegExp(escapeRegExp(fragment)));
	}
});

test("README glossary keeps the 9 canonical terms and dual-track semantics", () => {
	for (const fragment of [
		"### 术语表",
		"| Bro 模型 |",
		"| 内置模型 |",
		"| Path A |",
		"| Path B |",
		"| Vision Proxy |",
		"| Vision Agent |",
		"| GeometryProtocol |",
		"| Compatibility Matrix |",
		"| Request Attribution |",
		"### 视觉协议与双轨接入",
		"Path A：远端 OpenAI-compatible（Bro）模型主链路",
		"Path B：模型选择器中会出现运行时发现的 `(... Wrapped)` 内置模型",
		"modelSource = vscode-lm-wrapper"
	]) {
		assert.match(README, new RegExp(escapeRegExp(fragment)));
	}
});

test("README compatibility matrix rows stay aligned with runtime matrix entries", () => {
	const modelTypes: CompatibilityMatrixInput["modelType"][] = ["builtin", "bro"];
	const visionCapabilities: CompatibilityMatrixInput["visionCapability"][] = ["vision", "non-vision"];
	const toolsAvailability: CompatibilityMatrixInput["toolsAvailable"][] = ["tools-available", "no-tools"];
	const agentFlags: boolean[] = [true, false];

	for (const modelType of modelTypes) {
		for (const visionCapability of visionCapabilities) {
			for (const toolsAvailable of toolsAvailability) {
				for (const agentEnabled of agentFlags) {
					const input: CompatibilityMatrixInput = {
						modelType,
						visionCapability,
						toolsAvailable,
						agentEnabled
					};
					const entry = getCompatibilityMatrixEntry(input);
					const row = `| ${modelType} | ${visionCapability} | ${toReadmeToolsLabel(toolsAvailable)} | ${agentEnabled ? "on" : "off"} | ${entry.strategy} | ${entry.fallbackStrategy ?? "-"} |`;
					assert.match(README, new RegExp(escapeRegExp(row)));
				}
			}
		}
	}
});

function toReadmeToolsLabel(value: CompatibilityMatrixInput["toolsAvailable"]): "tools" | "no-tools" {
	return value === "tools-available" ? "tools" : "no-tools";
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}