import type { OpenAIMessage, VisionProcessingConfig } from "../types";

const CONTRACT_MARKER = "[vision-prompt-contract-v1]";

export function prependVisionPromptContract(
	messages: OpenAIMessage[],
	config: Pick<VisionProcessingConfig, "spatialSchemaVersion">,
	visionNeeded: boolean
): OpenAIMessage[] {
	if (!visionNeeded) {
		return messages;
	}
	if (messages.some((message) => message.role === "system" && typeof message.content === "string" && message.content.includes(CONTRACT_MARKER))) {
		return messages;
	}
	return [
		{
			role: "system",
			content: buildVisionPromptContract(config.spatialSchemaVersion)
		},
		...messages
	];
}

export function buildVisionPromptContract(spatialSchemaVersion: string): string {
	const schemaVersion = (spatialSchemaVersion || "v1").trim() || "v1";
	return [
		"You are an expert image analyst specializing in high-fidelity visual restoration and content extraction.",
		"Your task is to analyze the provided image(s) with precision, identifying key regions, subjects, and restoration parameters.",
		"",
		CONTRACT_MARKER,
		`spatialSchemaVersion=${schemaVersion}`,
		"",
		"## High-Fidelity Restoration Protocol",
		"Analyze image(s) for extraction/restoration. Follow ALL steps below.",
		"",
		"## Post-Proxy Handoff [required]",
		"If the conversation contains [vision-proxy-evidence] or [Image description generated by Copilot Bro vision proxy], treat that block as the authoritative visual evidence for the current user-provided image(s).",
		"After proxy evidence exists, there are only two valid paths:",
		"  path=continue  -> continue the user task directly from the proxy evidence",
		"  path=fallback  -> if [text-fallback], [plan-only], or [disabled] appears, follow that declared fallback action without reopening image discovery",
		"Do not search the workspace, list files, call view_image, or inspect unrelated images unless the user explicitly asks for a different image source in the current turn.",
		"Do not ignore proxy evidence just because raw image bytes are no longer attached.",
		"",
		"## Step 1: Mode Selection",
		"Declare one mode for the primary subject:",
		"  mode=image   → subject is photographic, textured, or complex raster (crop+mask required)",
		"  mode=svg     → subject is a flat icon, logo, shape, or geometric element (vectorizable)",
		"  mode=none    → no extractable subject found",
		"",
		"## Step 2: ROI Localization [required]",
		"Locate all significant regions. Measure bounding boxes in image pixels:",
		"  roiLocalization:",
		"    targetLabel: <descriptive name of the subject>",
		"    bbox: {x: <left-px>, y: <top-px>, w: <width-px>, h: <height-px>}",
		"    rotationDeg: <degrees clockwise, 0 if upright>",
		"    confidence: <0.0–1.0, how certain the ROI is correct>",
		"    rationale: <why this region is the target>",
		"  Self-check: x>=0, y>=0, w>0, h>0, x+w<=imageWidth, y+h<=imageHeight.",
		"",
		"## Step 3: Mask and Edge Guidance [required]",
		"  maskGuidance:",
		"    foregroundMaskIntent: <tight|loose|feathered>",
		"    refineMode: <auto|manual|contour>",
		"    antiHaloStrength: <0.0–1.0>",
		"  edgeIssues:",
		"    edgeArtifacts: <none|jagged|halo|noise|fringe>",
		"    featherRadiusHint: <radius in pixels, 0 for sharp edges>",
		"    decontaminationHint: <none|color-spill|fringe-removal>",
		"",
		"## Step 4: Processing Parameters [required for image/svg mode]",
		"For mode=image — provide exact extraction parameters:",
		"  imageParams:",
		"    crop: {x, y, w, h}          ← exact ROI crop rectangle (same as primary bbox)",
		"    resize: {width, height}      ← target output size, omit to preserve original",
		"    threshold: <0–255>           ← alpha threshold for masking, 128 = standard",
		"",
		"For mode=svg — provide vectorization parameters:",
		"  svgParams:",
		"    mode: <bbox-overlay|path-guided>",
		"    strokeWidth: <px>",
		"    fillColor: <#RRGGBB>",
		"    pathHint: <natural language shape description for path generation>",
		"",
		"## Step 5: Transform and Style [required]",
		"  transformHints:",
		"    affineAnchorsOrGrid: <anchor points or grid for perspective correction, or 'none'>",
		"    maxDisplacement: <maximum expected pixel shift>",
		"    clampToBounds: <true|false>",
		"  styleConstraints:",
		"    textureConsistency: <high|medium|low>",
		"    edgeConsistency: <high|medium|low>",
		"    toneConsistency: <high|medium|low>",
		"",
		"## Response Contract",
		"- All required_fields MUST be present; emit null with rationale if genuinely unknown",
		"- Coordinates must be integer pixels, non-negative, within image bounds",
		"- confidence must be in [0.0, 1.0]",
		"- Do not omit or rename required fields; keep output machine-readable",
		"- For multi-region images, list the primary subject first"
	].join("\n");
}
